"""changes of foreignkey name in bookbillboard table

Revision ID: 7c85d8f8479d
Revises: fb49725bb790
Create Date: 2024-02-06 15:12:34.020810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c85d8f8479d'
down_revision: Union[str, None] = 'fb49725bb790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_fullname', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_bookbillboard_booking_date_from', table_name='bookbillboard')
    op.drop_index('ix_bookbillboard_booking_date_to', table_name='bookbillboard')
    op.drop_index('ix_bookbillboard_booking_status', table_name='bookbillboard')
    op.drop_index('ix_bookbillboard_bookingbillboardid', table_name='bookbillboard')
    op.drop_index('ix_bookbillboard_total_days', table_name='bookbillboard')
    op.drop_table('bookbillboard')
    op.drop_index('ix_rolloutbillboard_location', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_picture', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_price', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_rolloutid', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_size', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_status', table_name='rolloutbillboard')
    op.drop_table('rolloutbillboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolloutbillboard',
    sa.Column('rolloutid', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.VARCHAR(), nullable=False),
    sa.Column('size', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('register_date', sa.VARCHAR(), nullable=False),
    sa.Column('picture', sa.VARCHAR(), nullable=False),
    sa.Column('fk_user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('rolloutid')
    )
    op.create_index('ix_rolloutbillboard_status', 'rolloutbillboard', ['status'], unique=False)
    op.create_index('ix_rolloutbillboard_size', 'rolloutbillboard', ['size'], unique=False)
    op.create_index('ix_rolloutbillboard_rolloutid', 'rolloutbillboard', ['rolloutid'], unique=False)
    op.create_index('ix_rolloutbillboard_price', 'rolloutbillboard', ['price'], unique=False)
    op.create_index('ix_rolloutbillboard_picture', 'rolloutbillboard', ['picture'], unique=False)
    op.create_index('ix_rolloutbillboard_location', 'rolloutbillboard', ['location'], unique=False)
    op.create_table('bookbillboard',
    sa.Column('bookingbillboardid', sa.INTEGER(), nullable=False),
    sa.Column('booking_status', sa.VARCHAR(), nullable=False),
    sa.Column('booking_date_from', sa.VARCHAR(), nullable=False),
    sa.Column('booking_date_to', sa.VARCHAR(), nullable=False),
    sa.Column('total_days', sa.INTEGER(), nullable=False),
    sa.Column('fk_user_id', sa.INTEGER(), nullable=False),
    sa.Column('fk_rollout_billboard_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['fk_rollout_billboard_id'], ['rolloutbillboard.rolloutid'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('bookingbillboardid')
    )
    op.create_index('ix_bookbillboard_total_days', 'bookbillboard', ['total_days'], unique=False)
    op.create_index('ix_bookbillboard_bookingbillboardid', 'bookbillboard', ['bookingbillboardid'], unique=False)
    op.create_index('ix_bookbillboard_booking_status', 'bookbillboard', ['booking_status'], unique=False)
    op.create_index('ix_bookbillboard_booking_date_to', 'bookbillboard', ['booking_date_to'], unique=False)
    op.create_index('ix_bookbillboard_booking_date_from', 'bookbillboard', ['booking_date_from'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(), nullable=False),
    sa.Column('phonenumber', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phonenumber')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_fullname', 'users', ['fullname'], unique=False)
    # ### end Alembic commands ###
