"""Added new fields to RollOutBillBoard asked by kebria in group

Revision ID: 9447c3771ecc
Revises: efcd003ca200
Create Date: 2024-03-13 12:38:56.397331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9447c3771ecc'
down_revision: Union[str, None] = 'efcd003ca200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookbillboard_booking_date_from', table_name='bookbillboard')
    op.drop_index('ix_bookbillboard_booking_date_to', table_name='bookbillboard')
    op.drop_index('ix_bookbillboard_booking_status', table_name='bookbillboard')
    op.drop_index('ix_bookbillboard_bookingbillboardid', table_name='bookbillboard')
    op.drop_index('ix_bookbillboard_total_days', table_name='bookbillboard')
    op.drop_table('bookbillboard')
    op.drop_index('ix_rolloutbillboard_installation', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_length', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_location', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_measurement_unit', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_picture', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_price', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_rolloutid', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_status', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_type', table_name='rolloutbillboard')
    op.drop_index('ix_rolloutbillboard_width', table_name='rolloutbillboard')
    op.drop_table('rolloutbillboard')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fullname', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phonenumber', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rolloutbillboard',
    sa.Column('rolloutid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('length', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('width', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('measurement_unit', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('installation', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('register_date', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('picture', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('fk_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], name='rolloutbillboard_ibfk_1'),
    sa.PrimaryKeyConstraint('rolloutid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rolloutbillboard_width', 'rolloutbillboard', ['width'], unique=False)
    op.create_index('ix_rolloutbillboard_type', 'rolloutbillboard', ['type'], unique=False)
    op.create_index('ix_rolloutbillboard_status', 'rolloutbillboard', ['status'], unique=False)
    op.create_index('ix_rolloutbillboard_rolloutid', 'rolloutbillboard', ['rolloutid'], unique=False)
    op.create_index('ix_rolloutbillboard_price', 'rolloutbillboard', ['price'], unique=False)
    op.create_index('ix_rolloutbillboard_picture', 'rolloutbillboard', ['picture'], unique=False)
    op.create_index('ix_rolloutbillboard_measurement_unit', 'rolloutbillboard', ['measurement_unit'], unique=False)
    op.create_index('ix_rolloutbillboard_location', 'rolloutbillboard', ['location'], unique=False)
    op.create_index('ix_rolloutbillboard_length', 'rolloutbillboard', ['length'], unique=False)
    op.create_index('ix_rolloutbillboard_installation', 'rolloutbillboard', ['installation'], unique=False)
    op.create_table('bookbillboard',
    sa.Column('bookingbillboardid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_status', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('booking_date_from', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('booking_date_to', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('total_days', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rollout_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fk_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], name='bookbillboard_ibfk_2'),
    sa.ForeignKeyConstraint(['rollout_id'], ['rolloutbillboard.rolloutid'], name='bookbillboard_ibfk_1'),
    sa.PrimaryKeyConstraint('bookingbillboardid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_bookbillboard_total_days', 'bookbillboard', ['total_days'], unique=False)
    op.create_index('ix_bookbillboard_bookingbillboardid', 'bookbillboard', ['bookingbillboardid'], unique=False)
    op.create_index('ix_bookbillboard_booking_status', 'bookbillboard', ['booking_status'], unique=False)
    op.create_index('ix_bookbillboard_booking_date_to', 'bookbillboard', ['booking_date_to'], unique=False)
    op.create_index('ix_bookbillboard_booking_date_from', 'bookbillboard', ['booking_date_from'], unique=False)
    # ### end Alembic commands ###
